### ISSUE TITLE
Backoff not kicking in, 100% usage on all CPUs

### ISSUE THREAD

**Issue by zevv** [mratsim/weave#103]
Running the following snippet makes my laptop hot, all CPUs spin at 100%

```
import weave, os

init(Weave)
os.sleep(10 * 1000)
exit(Weave)
```

Quick profiling indicates that CPU is spent in `tryRecv` / `recvProxy`

**Comment by zevv** [comment]
"Don't do that" is the proper answer, right? :) 

Thanks for your talk today, and it was a pleasure meeting you!

**Comment by mratsim** [comment]
Here is a way to do that:

```
import weave, os

init(Weave)
syncRoot(Weave)  # Empty the task queue
echo "Going to sleep"
os.sleep(10 * 1000)
echo "Waking up"
exit(Weave)
```

In your case what happens is:
- You create threads
- The main thread goes to sleep
- Child threads send steal request
- They get stuck in the main thread which is sleeping
- They can't sleep unless they are notified that there is no work
- The main thread wakes up
- Now it can handle the incoming requests

In short, similar to async/io don't block without handing back control to the scheduler otherwise mayhem ensues.

Unfortunately this is not solvable with Weave message-passing design. It would work if thefts were shared memory based, sleeping threads would not prevent active threads from looking in their deques but this tradeoff also prevents many optimizations.
